# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wavesmy/node/grpc/assets_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wavesmy import transaction_pb2 as wavesmy_dot_transaction__pb2
from wavesmy.node.grpc import accounts_api_pb2 as wavesmy_dot_node_dot_grpc_dot_accounts__api__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"wavesmy/node/grpc/assets_api.proto\x12\x11wavesmy.node.grpc\x1a\x19wavesmy/transaction.proto\x1a$wavesmy/node/grpc/accounts_api.proto\" \n\x0c\x41ssetRequest\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\x0c\"D\n\nNFTRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x16\n\x0e\x61\x66ter_asset_id\x18\x03 \x01(\x0c\"Y\n\x0bNFTResponse\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\x0c\x12\x38\n\nasset_info\x18\x02 \x01(\x0b\x32$.wavesmy.node.grpc.AssetInfoResponse\"\x96\x02\n\x11\x41ssetInfoResponse\x12\x0e\n\x06issuer\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08\x64\x65\x63imals\x18\x04 \x01(\x05\x12\x12\n\nreissuable\x18\x05 \x01(\x08\x12\x14\n\x0ctotal_volume\x18\x06 \x01(\x03\x12-\n\x06script\x18\x07 \x01(\x0b\x32\x1d.wavesmy.node.grpc.ScriptData\x12\x13\n\x0bsponsorship\x18\x08 \x01(\x03\x12\x35\n\x11issue_transaction\x18\x0b \x01(\x0b\x32\x1a.wavesmy.SignedTransaction\x12\x17\n\x0fsponsor_balance\x18\n \x01(\x03\x32\xac\x01\n\tAssetsApi\x12P\n\x07GetInfo\x12\x1f.wavesmy.node.grpc.AssetRequest\x1a$.wavesmy.node.grpc.AssetInfoResponse\x12M\n\nGetNFTList\x12\x1d.wavesmy.node.grpc.NFTRequest\x1a\x1e.wavesmy.node.grpc.NFTResponse0\x01\x42u\n\x1a\x63om.wavesplatform.api.grpcZEgithub.com/wavesplatform/gowaves/pkg/grpc/generated/wavesmy/node/grpc\xaa\x02\x0fWaves.Node.Grpcb\x06proto3')



_ASSETREQUEST = DESCRIPTOR.message_types_by_name['AssetRequest']
_NFTREQUEST = DESCRIPTOR.message_types_by_name['NFTRequest']
_NFTRESPONSE = DESCRIPTOR.message_types_by_name['NFTResponse']
_ASSETINFORESPONSE = DESCRIPTOR.message_types_by_name['AssetInfoResponse']
AssetRequest = _reflection.GeneratedProtocolMessageType('AssetRequest', (_message.Message,), {
  'DESCRIPTOR' : _ASSETREQUEST,
  '__module__' : 'wavesmy.node.grpc.assets_api_pb2'
  # @@protoc_insertion_point(class_scope:wavesmy.node.grpc.AssetRequest)
  })
_sym_db.RegisterMessage(AssetRequest)

NFTRequest = _reflection.GeneratedProtocolMessageType('NFTRequest', (_message.Message,), {
  'DESCRIPTOR' : _NFTREQUEST,
  '__module__' : 'wavesmy.node.grpc.assets_api_pb2'
  # @@protoc_insertion_point(class_scope:wavesmy.node.grpc.NFTRequest)
  })
_sym_db.RegisterMessage(NFTRequest)

NFTResponse = _reflection.GeneratedProtocolMessageType('NFTResponse', (_message.Message,), {
  'DESCRIPTOR' : _NFTRESPONSE,
  '__module__' : 'wavesmy.node.grpc.assets_api_pb2'
  # @@protoc_insertion_point(class_scope:wavesmy.node.grpc.NFTResponse)
  })
_sym_db.RegisterMessage(NFTResponse)

AssetInfoResponse = _reflection.GeneratedProtocolMessageType('AssetInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _ASSETINFORESPONSE,
  '__module__' : 'wavesmy.node.grpc.assets_api_pb2'
  # @@protoc_insertion_point(class_scope:wavesmy.node.grpc.AssetInfoResponse)
  })
_sym_db.RegisterMessage(AssetInfoResponse)

_ASSETSAPI = DESCRIPTOR.services_by_name['AssetsApi']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.wavesplatform.api.grpcZEgithub.com/wavesplatform/gowaves/pkg/grpc/generated/wavesmy/node/grpc\252\002\017Waves.Node.Grpc'
  _ASSETREQUEST._serialized_start=122
  _ASSETREQUEST._serialized_end=154
  _NFTREQUEST._serialized_start=156
  _NFTREQUEST._serialized_end=224
  _NFTRESPONSE._serialized_start=226
  _NFTRESPONSE._serialized_end=315
  _ASSETINFORESPONSE._serialized_start=318
  _ASSETINFORESPONSE._serialized_end=596
  _ASSETSAPI._serialized_start=599
  _ASSETSAPI._serialized_end=771
# @@protoc_insertion_point(module_scope)
