# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from wavesmy.node.grpc import transactions_api_pb2 as wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2
from wavesmy import transaction_pb2 as wavesmy_dot_transaction__pb2


class TransactionsApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTransactions = channel.unary_stream(
                '/wavesmy.node.grpc.TransactionsApi/GetTransactions',
                request_serializer=wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.TransactionsRequest.SerializeToString,
                response_deserializer=wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.TransactionResponse.FromString,
                )
        self.GetStateChanges = channel.unary_stream(
                '/wavesmy.node.grpc.TransactionsApi/GetStateChanges',
                request_serializer=wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.TransactionsRequest.SerializeToString,
                response_deserializer=wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.InvokeScriptResultResponse.FromString,
                )
        self.GetStatuses = channel.unary_stream(
                '/wavesmy.node.grpc.TransactionsApi/GetStatuses',
                request_serializer=wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.TransactionsByIdRequest.SerializeToString,
                response_deserializer=wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.TransactionStatus.FromString,
                )
        self.GetUnconfirmed = channel.unary_stream(
                '/wavesmy.node.grpc.TransactionsApi/GetUnconfirmed',
                request_serializer=wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.TransactionsRequest.SerializeToString,
                response_deserializer=wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.TransactionResponse.FromString,
                )
        self.Sign = channel.unary_unary(
                '/wavesmy.node.grpc.TransactionsApi/Sign',
                request_serializer=wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.SignRequest.SerializeToString,
                response_deserializer=wavesmy_dot_transaction__pb2.SignedTransaction.FromString,
                )
        self.Broadcast = channel.unary_unary(
                '/wavesmy.node.grpc.TransactionsApi/Broadcast',
                request_serializer=wavesmy_dot_transaction__pb2.SignedTransaction.SerializeToString,
                response_deserializer=wavesmy_dot_transaction__pb2.SignedTransaction.FromString,
                )


class TransactionsApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTransactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStateChanges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatuses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnconfirmed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sign(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Broadcast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionsApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTransactions': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTransactions,
                    request_deserializer=wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.TransactionsRequest.FromString,
                    response_serializer=wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.TransactionResponse.SerializeToString,
            ),
            'GetStateChanges': grpc.unary_stream_rpc_method_handler(
                    servicer.GetStateChanges,
                    request_deserializer=wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.TransactionsRequest.FromString,
                    response_serializer=wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.InvokeScriptResultResponse.SerializeToString,
            ),
            'GetStatuses': grpc.unary_stream_rpc_method_handler(
                    servicer.GetStatuses,
                    request_deserializer=wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.TransactionsByIdRequest.FromString,
                    response_serializer=wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.TransactionStatus.SerializeToString,
            ),
            'GetUnconfirmed': grpc.unary_stream_rpc_method_handler(
                    servicer.GetUnconfirmed,
                    request_deserializer=wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.TransactionsRequest.FromString,
                    response_serializer=wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.TransactionResponse.SerializeToString,
            ),
            'Sign': grpc.unary_unary_rpc_method_handler(
                    servicer.Sign,
                    request_deserializer=wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.SignRequest.FromString,
                    response_serializer=wavesmy_dot_transaction__pb2.SignedTransaction.SerializeToString,
            ),
            'Broadcast': grpc.unary_unary_rpc_method_handler(
                    servicer.Broadcast,
                    request_deserializer=wavesmy_dot_transaction__pb2.SignedTransaction.FromString,
                    response_serializer=wavesmy_dot_transaction__pb2.SignedTransaction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wavesmy.node.grpc.TransactionsApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TransactionsApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/wavesmy.node.grpc.TransactionsApi/GetTransactions',
            wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.TransactionsRequest.SerializeToString,
            wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.TransactionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStateChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/wavesmy.node.grpc.TransactionsApi/GetStateChanges',
            wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.TransactionsRequest.SerializeToString,
            wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.InvokeScriptResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatuses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/wavesmy.node.grpc.TransactionsApi/GetStatuses',
            wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.TransactionsByIdRequest.SerializeToString,
            wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.TransactionStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUnconfirmed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/wavesmy.node.grpc.TransactionsApi/GetUnconfirmed',
            wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.TransactionsRequest.SerializeToString,
            wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.TransactionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Sign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wavesmy.node.grpc.TransactionsApi/Sign',
            wavesmy_dot_node_dot_grpc_dot_transactions__api__pb2.SignRequest.SerializeToString,
            wavesmy_dot_transaction__pb2.SignedTransaction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Broadcast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wavesmy.node.grpc.TransactionsApi/Broadcast',
            wavesmy_dot_transaction__pb2.SignedTransaction.SerializeToString,
            wavesmy_dot_transaction__pb2.SignedTransaction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
