# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wavesmy/amount.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14wavesmy/amount.proto\x12\x07wavesmy\"*\n\x06\x41mount\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\x0c\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x03\x42\x61\n\x1a\x63om.wavesplatform.protobufZ;github.com/wavesplatform/gowaves/pkg/grpc/generated/wavesmy\xaa\x02\x05Wavesb\x06proto3')



_AMOUNT = DESCRIPTOR.message_types_by_name['Amount']
Amount = _reflection.GeneratedProtocolMessageType('Amount', (_message.Message,), {
  'DESCRIPTOR' : _AMOUNT,
  '__module__' : 'wavesmy.amount_pb2'
  # @@protoc_insertion_point(class_scope:wavesmy.Amount)
  })
_sym_db.RegisterMessage(Amount)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.wavesplatform.protobufZ;github.com/wavesplatform/gowaves/pkg/grpc/generated/wavesmy\252\002\005Waves'
  _AMOUNT._serialized_start=33
  _AMOUNT._serialized_end=75
# @@protoc_insertion_point(module_scope)
