# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wavesmy/block.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wavesmy import transaction_pb2 as wavesmy_dot_transaction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13wavesmy/block.proto\x12\x07wavesmy\x1a\x19wavesmy/transaction.proto\"\xd4\x02\n\x05\x42lock\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.wavesmy.Block.Header\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12\x30\n\x0ctransactions\x18\x03 \x03(\x0b\x32\x1a.wavesmy.SignedTransaction\x1a\xde\x01\n\x06Header\x12\x10\n\x08\x63hain_id\x18\x01 \x01(\x05\x12\x11\n\treference\x18\x02 \x01(\x0c\x12\x13\n\x0b\x62\x61se_target\x18\x03 \x01(\x03\x12\x1c\n\x14generation_signature\x18\x04 \x01(\x0c\x12\x15\n\rfeature_votes\x18\x05 \x03(\r\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x12\x0f\n\x07version\x18\x07 \x01(\x05\x12\x11\n\tgenerator\x18\x08 \x01(\x0c\x12\x13\n\x0breward_vote\x18\t \x01(\x03\x12\x19\n\x11transactions_root\x18\n \x01(\x0c\"\x9e\x01\n\nMicroBlock\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x11\n\treference\x18\x02 \x01(\x0c\x12\x1f\n\x17updated_block_signature\x18\x03 \x01(\x0c\x12\x19\n\x11sender_public_key\x18\x04 \x01(\x0c\x12\x30\n\x0ctransactions\x18\x05 \x03(\x0b\x32\x1a.wavesmy.SignedTransaction\"g\n\x10SignedMicroBlock\x12(\n\x0bmicro_block\x18\x01 \x01(\x0b\x32\x13.wavesmy.MicroBlock\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12\x16\n\x0etotal_block_id\x18\x03 \x01(\x0c\x42g\n com.wavesplatform.protobuf.blockZ;github.com/wavesplatform/gowaves/pkg/grpc/generated/wavesmy\xaa\x02\x05Wavesb\x06proto3')



_BLOCK = DESCRIPTOR.message_types_by_name['Block']
_BLOCK_HEADER = _BLOCK.nested_types_by_name['Header']
_MICROBLOCK = DESCRIPTOR.message_types_by_name['MicroBlock']
_SIGNEDMICROBLOCK = DESCRIPTOR.message_types_by_name['SignedMicroBlock']
Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), {

  'Header' : _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {
    'DESCRIPTOR' : _BLOCK_HEADER,
    '__module__' : 'wavesmy.block_pb2'
    # @@protoc_insertion_point(class_scope:wavesmy.Block.Header)
    })
  ,
  'DESCRIPTOR' : _BLOCK,
  '__module__' : 'wavesmy.block_pb2'
  # @@protoc_insertion_point(class_scope:wavesmy.Block)
  })
_sym_db.RegisterMessage(Block)
_sym_db.RegisterMessage(Block.Header)

MicroBlock = _reflection.GeneratedProtocolMessageType('MicroBlock', (_message.Message,), {
  'DESCRIPTOR' : _MICROBLOCK,
  '__module__' : 'wavesmy.block_pb2'
  # @@protoc_insertion_point(class_scope:wavesmy.MicroBlock)
  })
_sym_db.RegisterMessage(MicroBlock)

SignedMicroBlock = _reflection.GeneratedProtocolMessageType('SignedMicroBlock', (_message.Message,), {
  'DESCRIPTOR' : _SIGNEDMICROBLOCK,
  '__module__' : 'wavesmy.block_pb2'
  # @@protoc_insertion_point(class_scope:wavesmy.SignedMicroBlock)
  })
_sym_db.RegisterMessage(SignedMicroBlock)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.wavesplatform.protobuf.blockZ;github.com/wavesplatform/gowaves/pkg/grpc/generated/wavesmy\252\002\005Waves'
  _BLOCK._serialized_start=60
  _BLOCK._serialized_end=400
  _BLOCK_HEADER._serialized_start=178
  _BLOCK_HEADER._serialized_end=400
  _MICROBLOCK._serialized_start=403
  _MICROBLOCK._serialized_end=561
  _SIGNEDMICROBLOCK._serialized_start=563
  _SIGNEDMICROBLOCK._serialized_end=666
# @@protoc_insertion_point(module_scope)
