# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wavesmy/order.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wavesmy import amount_pb2 as wavesmy_dot_amount__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13wavesmy/order.proto\x12\x07wavesmy\x1a\x14wavesmy/amount.proto\"<\n\tAssetPair\x12\x17\n\x0f\x61mount_asset_id\x18\x01 \x01(\x0c\x12\x16\n\x0eprice_asset_id\x18\x02 \x01(\x0c\"\xe1\x03\n\x05Order\x12\x10\n\x08\x63hain_id\x18\x01 \x01(\x05\x12\x1a\n\x12matcher_public_key\x18\x03 \x01(\x0c\x12&\n\nasset_pair\x18\x04 \x01(\x0b\x32\x12.wavesmy.AssetPair\x12\'\n\norder_side\x18\x05 \x01(\x0e\x32\x13.wavesmy.Order.Side\x12\x0e\n\x06\x61mount\x18\x06 \x01(\x03\x12\r\n\x05price\x18\x07 \x01(\x03\x12\x11\n\ttimestamp\x18\x08 \x01(\x03\x12\x12\n\nexpiration\x18\t \x01(\x03\x12$\n\x0bmatcher_fee\x18\n \x01(\x0b\x32\x0f.wavesmy.Amount\x12\x0f\n\x07version\x18\x0b \x01(\x05\x12\x0e\n\x06proofs\x18\x0c \x03(\x0c\x12,\n\nprice_mode\x18\x0e \x01(\x0e\x32\x18.wavesmy.Order.PriceMode\x12\x1b\n\x11sender_public_key\x18\x02 \x01(\x0cH\x00\x12\x1a\n\x10\x65ip712_signature\x18\r \x01(\x0cH\x00\"\x19\n\x04Side\x12\x07\n\x03\x42UY\x10\x00\x12\x08\n\x04SELL\x10\x01\"@\n\tPriceMode\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x12\n\x0e\x46IXED_DECIMALS\x10\x01\x12\x12\n\x0e\x41SSET_DECIMALS\x10\x02\x42\x08\n\x06senderBg\n com.wavesplatform.protobuf.orderZ;github.com/wavesplatform/gowaves/pkg/grpc/generated/wavesmy\xaa\x02\x05Wavesb\x06proto3')



_ASSETPAIR = DESCRIPTOR.message_types_by_name['AssetPair']
_ORDER = DESCRIPTOR.message_types_by_name['Order']
_ORDER_SIDE = _ORDER.enum_types_by_name['Side']
_ORDER_PRICEMODE = _ORDER.enum_types_by_name['PriceMode']
AssetPair = _reflection.GeneratedProtocolMessageType('AssetPair', (_message.Message,), {
  'DESCRIPTOR' : _ASSETPAIR,
  '__module__' : 'wavesmy.order_pb2'
  # @@protoc_insertion_point(class_scope:wavesmy.AssetPair)
  })
_sym_db.RegisterMessage(AssetPair)

Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), {
  'DESCRIPTOR' : _ORDER,
  '__module__' : 'wavesmy.order_pb2'
  # @@protoc_insertion_point(class_scope:wavesmy.Order)
  })
_sym_db.RegisterMessage(Order)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.wavesplatform.protobuf.orderZ;github.com/wavesplatform/gowaves/pkg/grpc/generated/wavesmy\252\002\005Waves'
  _ASSETPAIR._serialized_start=54
  _ASSETPAIR._serialized_end=114
  _ORDER._serialized_start=117
  _ORDER._serialized_end=598
  _ORDER_SIDE._serialized_start=497
  _ORDER_SIDE._serialized_end=522
  _ORDER_PRICEMODE._serialized_start=524
  _ORDER_PRICEMODE._serialized_end=588
# @@protoc_insertion_point(module_scope)
