# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wavesmy/recipient.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17wavesmy/recipient.proto\x12\x07wavesmy\"D\n\tRecipient\x12\x19\n\x0fpublic_key_hash\x18\x01 \x01(\x0cH\x00\x12\x0f\n\x05\x61lias\x18\x02 \x01(\tH\x00\x42\x0b\n\trecipientBm\n&com.wavesplatform.protobuf.transactionZ;github.com/wavesplatform/gowaves/pkg/grpc/generated/wavesmy\xaa\x02\x05Wavesb\x06proto3')



_RECIPIENT = DESCRIPTOR.message_types_by_name['Recipient']
Recipient = _reflection.GeneratedProtocolMessageType('Recipient', (_message.Message,), {
  'DESCRIPTOR' : _RECIPIENT,
  '__module__' : 'wavesmy.recipient_pb2'
  # @@protoc_insertion_point(class_scope:wavesmy.Recipient)
  })
_sym_db.RegisterMessage(Recipient)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n&com.wavesplatform.protobuf.transactionZ;github.com/wavesplatform/gowaves/pkg/grpc/generated/wavesmy\252\002\005Waves'
  _RECIPIENT._serialized_start=36
  _RECIPIENT._serialized_end=104
# @@protoc_insertion_point(module_scope)
